### ISSUE TITLE
Excuse me, ask about ALIIOS - Automatic Landmarks Identification for Intra OralScans

### ISSUE THREAD

**Issue by 3dsfgs** [juanprietob/textureSynthesis#4]
What exactly do these four parameters represent? Do you want to put the path of the file in the first place, the data in the vtk format in the second place, and the grid data in the third place? How do I get the last. csv file? What is the function
Can you upload a folder with complete training steps?
How to train the data set defined by myself? I now have a lot of data scanned by ios, about 200 vtp data. How should I use these data for training?
I downloaded your previous weight file. How should I test it? I have been watching for 7 hours, but I still can't understand the operation principle of your project. I admit I'm stupid.
I hope you can tell me, thank you very much
https://github.com/baptistebaquero/ALIDDM
I think you are a team, so I come here to inquire and look forward to your reply. Thank you！

**Comment by juanprietob** [comment]
Hello, 
For ALIDDM questions please post them in the correct issues forum. 
Thanks.

**Comment by 3dsfgs** [comment]
Sorry, I didn't do this intentionally. I really want to know how ALIIos works, so I'm sorry that I did this. I saw that you are related to him, so I made a comment under the forum other than ALIIos. Sorry, I was too worried

**Comment by juanprietob** [comment]
Please post you question here https://github.com/DCBIA-OrthoLab/ALIDDM/issues
